<script type="text/javascript" src="/js/lib/lodash.min.js"></script>
<script type="text/javascript" src="/vendor/components/jquery/jquery.min.js"></script>
<script type="text/javascript" src="/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/vendor/ckeditor/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/lib/bscombobox/js/bootstrap-combobox.js"></script>
<script type="text/javascript" src="/js/lib/DataTables/DataTables-1.10.9/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/lib/DataTables/DataTables-1.10.9/js/dataTables.bootstrap.min.js"></script>
<script type="text/javascript" src="/js/lib/DataTables/Responsive-1.0.7/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="/js/utils.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
